<a href="https://colab.research.google.com/github/Vitela-debug/Colab_S1_Clase-de-progralaci-n_273522_TVB/blob/main/sesion10_data_profiling_entregable_273522.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Sesión 10 — Entregable sobre Data Profiling

**Nombre completo: Tania Vitela Barraza**

**Matrícula: 273522**

---

Este notebook contiene las actividades a entregar de la Sesión 10 (Data Profiling), aplicadas sobre **datasets reales**: el catálogo de Netflix y el dataset de Customer Personality Analysis (Kaggle). Si aún no revisaste las explicaciones y ejemplos de cada tema, hazlo primero en el notebook `Sesion10_Data_Profiling_Actividad_Asincrona.ipynb`.

**Nota sobre los datos:** ambos datasets son reales — los problemas de calidad que vas a encontrar (nulos, categorías inconsistentes, valores fuera de rango) ya existían antes de que este notebook los usara. La única excepción está marcada explícitamente en la Actividad 3 y la Práctica integradora, donde se inyectan un par de filas/valores a propósito para poder practicar duplicados y ajuste de tipos con un resultado garantizado.

**Antes de entregar:** ejecuta "Reiniciar y ejecutar todo" para confirmar que tu notebook corre de principio a fin sin errores.

## Preparación

Ejecuta esta celda antes de empezar — descarga los dos datasets reales que vas a usar.

In [ ]:
import pandas as pd

url_netflix = 'https://raw.githubusercontent.com/Vibe1990/Netflix-Project/main/netflix_title.csv'
url_marketing = 'https://raw.githubusercontent.com/amankharwal/Website-data/master/marketing_campaign.csv'

df_netflix = pd.read_csv(url_netflix)
df_marketing = pd.read_csv(url_marketing, sep=';')  # nota: este archivo usa punto y coma, no coma

print('Netflix:', df_netflix.shape)
print('Marketing:', df_marketing.shape)

Netflix: (7787, 12)
Marketing: (2240, 29)

---
## Actividad 1 — Renombrado y estandarización de columnas

*Dataset: Customer Personality Analysis*

Revisa los nombres de columna de `df_marketing` con `.columns`. Vas a notar una mezcla de convenciones reales: `Year_Birth` (con guion bajo), `Kidhome` (sin separador), `MntWines` (abreviado y sin separador).

**Trabaja sobre una copia** (`df_marketing_renombrado = df_marketing.copy()`) para no afectar las actividades siguientes, que usan los nombres originales. Aplica `.str.lower()` para al menos unificar mayúsculas/minúsculas, y usa `.rename()` para corregir manualmente los 2-3 nombres que la técnica automática no deja perfectos (por ejemplo, `mntwines` sigue sin ser ideal — decide tú el nombre final).

In [ ]:
# Tu código aquí
df_marketing.shape #para revisar la cantidad de filas  columnas

(2240, 29)

In [ ]:
# Tu código aquí
df_marketing.columns #para revisar el nombre de las columnas

Index(['ID', 'Year_Birth', 'Education', 'Marital_Status', 'Income', 'Kidhome',
       'Teenhome', 'Dt_Customer', 'Recency', 'MntWines', 'MntFruits',
       'MntMeatProducts', 'MntFishProducts', 'MntSweetProducts',
       'MntGoldProds', 'NumDealsPurchases', 'NumWebPurchases',
       'NumCatalogPurchases', 'NumStorePurchases', 'NumWebVisitsMonth',
       'AcceptedCmp3', 'AcceptedCmp4', 'AcceptedCmp5', 'AcceptedCmp1',
       'AcceptedCmp2', 'Complain', 'Z_CostContact', 'Z_Revenue', 'Response'],
      dtype='object')

In [ ]:
df_marketing.columns.tolist() #para verlo en forma de lista (personalmente creo que es mas visible)

['ID',
 'Year_Birth',
 'Education',
 'Marital_Status',
 'Income',
 'Kidhome',
 'Teenhome',
 'Dt_Customer',
 'Recency',
 'MntWines',
 'MntFruits',
 'MntMeatProducts',
 'MntFishProducts',
 'MntSweetProducts',
 'MntGoldProds',
 'NumDealsPurchases',
 'NumWebPurchases',
 'NumCatalogPurchases',
 'NumStorePurchases',
 'NumWebVisitsMonth',
 'AcceptedCmp3',
 'AcceptedCmp4',
 'AcceptedCmp5',
 'AcceptedCmp1',
 'AcceptedCmp2',
 'Complain',
 'Z_CostContact',
 'Z_Revenue',
 'Response']

In [ ]:
# Tu código aquí
df_marketing_renombrado = df_marketing.copy() #le sacamos copia al df y trabajamos con la copia
df_marketing_renombrado.columns  = df_marketing_renombrado.columns.str.lower() #Hacemos todas las letras minusculas
df_marketing_renombrado.columns.tolist() #lo vemos en lista

['id',
 'year_birth',
 'education',
 'marital_status',
 'income',
 'kidhome',
 'teenhome',
 'dt_customer',
 'recency',
 'mntwines',
 'mntfruits',
 'mntmeatproducts',
 'mntfishproducts',
 'mntsweetproducts',
 'mntgoldprods',
 'numdealspurchases',
 'numwebpurchases',
 'numcatalogpurchases',
 'numstorepurchases',
 'numwebvisitsmonth',
 'acceptedcmp3',
 'acceptedcmp4',
 'acceptedcmp5',
 'acceptedcmp1',
 'acceptedcmp2',
 'complain',
 'z_costcontact',
 'z_revenue',
 'response']

In [ ]:
# Tu código aquí
# .rename(columns={...}) recibe un diccionario: nombre viejo (clave) -> nombre nuevo (valor).
# Cada columna se renombra explícitamente, una por una.
df_marketing_renombrado = df_marketing_renombrado.rename(columns={
    'kidhome': 'kid_home',
    'teenhome': 'teen_home',
    'mntwines': 'mnt_wines',
    'mntfruits': 'mnt_fruits',
    'mntmeatproducts': 'mnt_meat_products',
    'mntfishproducts': 'mnt_fish_products',
    'mntsweetproducts': 'mnt_sweet_products',
    'mntgoldprods': 'mnt_gold_prods',
    'numdealspurchases': 'num_deal_purchases',
    'numwebpurchases': 'num_web_purchases',
    'numcatalogpurchases': 'num_catalog_purchases',
    'numstorepurchases': 'num_store_purchases',
    'numwebvisitsmonth': 'num_web_visits_month',
    'acceptedcmp3': 'accepted_cmp_3',
    'acceptedcmp4': 'accepted_cmp_4',
    'acceptedcmp5': 'accepted_cmp_5',
    'acceptedcmp1': 'accepted_cmp_1',
    'acceptedcmp2': 'accepted_cmp_2',
    'z_costcontact': 'z_cost_contact'
})
df_marketing_renombrado.columns.tolist()

['id',
 'year_birth',
 'education',
 'marital_status',
 'income',
 'kid_home',
 'teen_home',
 'dt_customer',
 'recency',
 'mnt_wines',
 'mnt_fruits',
 'mnt_meat_products',
 'mnt_fish_products',
 'mnt_sweet_products',
 'mnt_gold_prods',
 'num_deal_purchases',
 'num_web_purchases',
 'num_catalog_purchases',
 'num_store_purchases',
 'num_web_visits_month',
 'accepted_cmp_3',
 'accepted_cmp_4',
 'accepted_cmp_5',
 'accepted_cmp_1',
 'accepted_cmp_2',
 'complain',
 'z_cost_contact',
 'z_revenue',
 'response']

---
---
* Para la actividad 1 el código permite realizar las siguientes actividades:
* `df_marketing.shape` se utilizó para saber cuántas filas y columnas tiene mi DataFrame.
* `df_marketing.columns` se utilizó para ver el nombre de todas las columnas que tiene el DataFrame.
* `df_marketing.columns.tolist()` se utilizó para convertir los nombres de las columnas en una lista, porque así se me hace más fácil visualizarlas y revisarlas.
* `df_marketing_renombrado = df_marketing.copy()` se utilizó para crear una copia del DataFrame original y trabajar sobre ella sin modificar el original mientras que `df_marketing_renombrado.columns = df_marketing_renombrado.columns.str.lower()` se utilizó para convertir todos los nombres de las columnas a minúsculas.
* `df_marketing_renombrado.columns.tolist() `se utilizó nuevamente para revisar cómo quedaron los nombres de las columnas después de convertirlos a minúsculas.
* `df_marketing_renombrado.rename(columns={...}) `se utilizó para cambiar el nombre de algunas columnas y agregar _ donde hacía falta, haciendo que los nombres fueran más fáciles de leer, todo esto de forma manual es decir se escribió el nombre de la columna original y luego el deseado en forma de diccionario.
* Finalmente `df_marketing_renombrado.columns.tolist()` se utilizó al final para comprobar que los nombres de las columnas quedaron correctamente modificados.
---
---

---
## Actividad 2 — Ajuste de tipos: fechas con formato mixto

*Dataset: Netflix*

La columna `date_added` de `df_netflix` mezcla formatos reales: la mayoría son `"14-Aug-20"`, pero un grupo minoritario llega como `" August 4, 2017"` (con espacio inicial). Conviértela a tipo fecha usando `pd.to_datetime(..., format='mixed')`, que resuelve ambos formatos en la misma columna. Verifica con `.dtypes` y confirma cuántos valores nulos quedan después de la conversión (compara contra los nulos que ya traía antes de convertir).

In [ ]:
# Tu código aquí
# Revisar los tipos de datos antes de hacer la conversión lo esperado son objects
print("Tipos de datos antes de la conversión:", df_netflix['date_added'].dtypes)

# Revisar cuántos valores nulos tiene date_added antes de convertirla
nulos_antes = df_netflix['date_added'].isna().sum()
print("Nulos antes:", nulos_antes)

#Visualizar los nulos antes
df_netflix.loc[df_netflix['date_added'].isna(), 'date_added']

Tipos de datos antes de la conversión: object
Nulos antes: 10

258     NaN
549     NaN
2263    NaN
2288    NaN
2555    NaN
3374    NaN
3492    NaN
3946    NaN
5137    NaN
6065    NaN
Name: date_added, dtype: object

In [ ]:
# Convertir date_added a formato fecha, permitiendo formatos mixtos (fechas escritas de diferentes maneras)
df_netflix['date_added'] = pd.to_datetime(df_netflix['date_added'], format='mixed')

# Revisar los tipos de datos después de la conversión lo esperado es datetime
print("Tipos de datos despues de la conversión:", df_netflix['date_added'].dtypes)

# Revisar cuántos valores nulos quedaron después de la conversión
nulos_despues = df_netflix['date_added'].isna().sum()
print("Nulos después:", nulos_despues)

#Visualizar los nulos despues de la conversion
df_netflix.loc[df_netflix['date_added'].isna(), 'date_added']

Tipos de datos despues de la conversión: datetime64[ns]
Nulos después: 10

258    NaT
549    NaT
2263   NaT
2288   NaT
2555   NaT
3374   NaT
3492   NaT
3946   NaT
5137   NaT
6065   NaT
Name: date_added, dtype: datetime64[ns]

In [ ]:
print("Los valores nulos antes y despues son iguales:", nulos_antes == nulos_despues )

Los valores nulos antes y despues son iguales: True

---
---
* El código de la actividad 2 primero revisa el tipo de dato de date_added y la cantidad de valores nulos que tenía antes de la conversión mediante `df_netflix['date_added'].dtypes` y `df_netflix['date_added'].isna().sum()` para contar los nulos. Después se utiliza `pd.to_datetime()` con `format='mixed'` porque la columna contiene fechas en diferentes formatos, lo que permite que pandas reconozca diferente tipo de fechas, de tal forma que, la columna cambió de object a datetime64[ns]. Los valores nulos se mantuvieron en 10 porque ya estaban vacíos antes de la conversión y `pd.to_datetime()` no rellena estos valores, solamente convierte las fechas que sí tienen información. Por lo tanto, que los nulos sean los mismos antes y después indica que no se generaron nuevos valores nulos durante la conversión.
---
---

---
## Actividad 3 — Duplicados

*Dataset: Customer Personality Analysis — con 2 filas duplicadas inyectadas a propósito*

Este dataset real no trae duplicados de forma natural — para poder practicar, se insertan 2 copias de clientes ya existentes (ejecuta la celda siguiente).

In [ ]:
df_marketing_dup = pd.concat([df_marketing, df_marketing.sample(2, random_state=7)], ignore_index=True)
print('Filas originales:', len(df_marketing))
print('Filas con duplicados inyectados:', len(df_marketing_dup))

Filas originales: 2240
Filas con duplicados inyectados: 2242

Sobre `df_marketing_dup`: cuenta los duplicados exactos con `.duplicated().sum()`, luego cuenta los duplicados por `ID` con `.duplicated(subset='ID').sum()` (deberían coincidir, ya que el `ID` es único por cliente). Elimínalos con `.drop_duplicates()` y confirma el número final de filas.

In [ ]:
# Tu código aquí
print("Duplicados exactos en df_marketing_dup:", df_marketing_dup.duplicated().sum()) #Para contar los duplicados de todo el df
print("Duplicados por ID en df_maarketing_dup:", df_marketing_dup.duplicated(subset='ID').sum()) #para contar los duplicados por ID
#Visualizar los duplicados por ID
print("Duplicados por ID en df_maarketing_dup:")
df_marketing_dup[df_marketing_dup.duplicated(subset='ID')]

Duplicados exactos en df_marketing_dup: 2
Duplicados por ID en df_maarketing_dup: 2
Duplicados por ID en df_maarketing_dup:

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
2240,7059,1963,Graduation,Married,80124.0,0,0,2014-06-26,47,483,...,1,1,0,0,0,0,0,3,11,0
2241,1606,1971,Graduation,Together,38590.0,1,0,2013-05-15,65,3,...,8,0,0,0,0,0,0,3,11,0

In [ ]:
#Eliminar duplicados con .drop_duplicates()
df_marketing_dup = df_marketing_dup.drop_duplicates()
print("Duplicados aplicando la eliminacion:", df_marketing_dup.duplicated(subset='ID').sum())
print("Filas sin duplicados:", len(df_marketing_dup))

Duplicados aplicando la eliminacion: 0
Filas sin duplicados: 2240

---
---
* Para la Actividad 3 se reviso como ver los duplicados en las filas para los datos en general y para columnas en especifico, mediante las siguientes herramientas:
* `df_marketing_dup.duplicated().sum()` se utilizó para contar cuántas filas están completamente duplicadas en todo el DataFrame, es decir, filas donde todos sus datos son iguales.
* `df_marketing_dup.duplicated(subset='ID').sum()` se utilizó para contar cuántos IDs están repetidos, tomando únicamente la columna ID para identificar los duplicados.
* `df_marketing_dup[df_marketing_dup.duplicated(subset='ID')]` se utilizó para visualizar las filas que tienen un ID repetido, mostrando las apariciones que pandas considera duplicadas.
* `df_marketing_dup.drop_duplicates()` se utilizó para eliminar las filas que están completamente duplicadas, dejando solamente una copia de cada fila idéntica.
* `df_marketing_dup.duplicated(subset='ID').sum() `después de la eliminación se utilizó para volver a contar los IDs duplicados y comprobar si todavía existen repetidos (se esperaba un valor 0 para comprobar).
* `len(df_marketing_dup)` se utilizó para saber cuántas filas tiene el DataFrame después de eliminar los duplicados y comprobar que fueran como las originales antes de inyectar los duplicados.
---
---

---
## Actividad 4 — Valores faltantes

*Dataset: Netflix*

Usa `.isnull().sum()` sobre `df_netflix` para ver cuántos valores faltan por columna. Luego, usa `.isnull().any(axis=1)` para filtrar solo las filas que tienen **al menos un** valor faltante en cualquier columna, y muestra cuántas filas son en total (`.sum()` sobre el resultado booleano).

In [ ]:
# Tu código aquí
df_netflix.isnull().sum() #para contar los valores faltantes por columna

show_id            0
type               0
title              0
director        2389
cast             718
country          507
date_added        10
release_year       0
rating             7
duration           0
listed_in          0
description        0
dtype: int64

In [ ]:
# Tu código aquí
df_netflix.isnull().any(axis=1) #Para filtrar las filas que tienen al menos 1 valor faltante

0        True
1       False
2       False
3       False
4       False
        ...
7782    False
7783    False
7784     True
7785     True
7786     True
Length: 7787, dtype: bool

In [ ]:
df_netflix[df_netflix.isnull().any(axis=1)] #	Muestra las filas con faltantes

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,2020-08-14,2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
11,s12,TV Show,1983,NaN,"Robert Więckiewicz, Maciej Musiał, Michalina O...","Poland, United States",2018-11-30,2018,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Dramas","In this dark alt-history thriller, a naïve law..."
12,s13,TV Show,1994,Diego Enrique Osorno,NaN,Mexico,2019-05-17,2019,TV-MA,1 Season,"Crime TV Shows, Docuseries, International TV S...",Archival video and new interviews examine Mexi...
16,s17,TV Show,09-Feb,NaN,"Shahd El Yaseen, Shaila Sabt, Hala, Hanadi Al-...",NaN,2019-03-20,2018,TV-14,1 Season,"International TV Shows, TV Dramas","As a psychology professor faces Alzheimer's, h..."
19,s20,Movie,'89,NaN,"Lee Dixon, Ian Wright, Paul Merson",United Kingdom,2018-05-16,2017,TV-PG,87 min,Sports Movies,"Mixing old footage with interviews, this is th..."
...,...,...,...,...,...,...,...,...,...,...,...,...
7777,s7778,TV Show,Zombie Dumb,NaN,NaN,NaN,2019-07-01,2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
7779,s7780,TV Show,Zona Rosa,NaN,"Manu NNa, Ana Julia Yeyé, Ray Contreras, Pablo...",Mexico,2019-11-26,2019,TV-MA,1 Season,"International TV Shows, Spanish-Language TV Sh...",An assortment of talent takes the stage for a ...
7784,s7785,Movie,Zulu Man in Japan,NaN,Nasty C,NaN,2020-09-25,2019,TV-MA,44 min,"Documentaries, International Movies, Music & M...","In this documentary, South African rapper Nast..."
7785,s7786,TV Show,Zumbo's Just Desserts,NaN,"Adriano Zumbo, Rachel Khoo",Australia,2020-10-31,2019,TV-PG,1 Season,"International TV Shows, Reality TV",Dessert wizard Adriano Zumbo looks for the nex...
7786,s7787,Movie,ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS,Sam Dunn,NaN,"United Kingdom, Canada, United States",2020-03-01,2019,TV-MA,90 min,"Documentaries, Music & Musicals",This documentary delves into the mystique behi...

In [ ]:
#Tu código aquí
print("Filas totales con datos faltantes:", df_netflix.isnull().any(axis=1).sum() ) #Para contar cuantas filas tienen al menos 1 valor faltante

Filas totales con datos faltantes: 2979

---
---
* El código de la Actividad 4 revisa los datos para identificar los valores que hacen falta.
*  `df_netflix.isnull().sum()` cuento cuántos datos faltantes hay en cada columna
* `df_netflix.isnull().any(axis=1)` ise usa pra identificar  las filas que tienen por lo menos un dato faltante.
*  `df_netflix[df_netflix.isnull().any(axis=1)] ` es interensate porque filtra la información para mostrar únicamente esas filas y poder revisarlas (las que tienen un valor faltante) .
* `df_netflix.isnull().any(axis=1).sum()` cuento el total de filas que tienen al menos un dato faltante.
* En terminos generales sirve para conocer la cantidad de información incompleta que tiene la base de datos y saber qué registros necesitan ser revisados o corregidos.
---
---

---
## Actividad 5 — Completitud como porcentaje

*Dataset: Netflix*

Con los mismos nulos de la Actividad 4, calcula la completitud en porcentaje por columna: `(1 - nulos / total_filas) * 100`. ¿Qué columna tiene la completitud más baja? Escribe la respuesta en una línea.

In [ ]:
# Tu código aquí
# len(df_netflix) da el número total de filas -- lo usamos como base para calcular el porcentaje.
total_registros = len(df_netflix)
# (1 - proporción_de_nulos) * 100 = porcentaje de valores presentes.
completitud = (1 - df_netflix.isnull().sum() / total_registros) * 100
completitud

show_id         100.000000
type            100.000000
title           100.000000
director         69.320663
cast             90.779504
country          93.489149
date_added       99.871581
release_year    100.000000
rating           99.910107
duration        100.000000
listed_in       100.000000
description     100.000000
dtype: float64

In [ ]:
columna_minima = completitud.idxmin()  #idxmin() busca el nombre de la columna que tiene el valor más pequeño.
print("La columna con menor completitud es:", columna_minima) #para sacar la columna que tiene más valores faltantes proporcionalmente
print("Su completitud es:", completitud.min(), "%")  #para sacar el valor con  la columna que tiene más valores faltantes proporcionalmente en terminos de %

La columna con menor completitud es: director
Su completitud es: 69.32066264286631 %

---
---
* El código de la Actividad 5 primero calcula el número total de registros de la base de datos con `len(df_netflix)` para tener una cantidad de referencia y poder calcular los porcentajes.
8 `df_netflix.isnull().sum()` cuenta los valores faltantes de cada columna y con la fórmula `(1 - nulos / total_filas) * 100` se calcula el porcentaje de datos que sí están completos en cada una.
* Con completitud se puede  ver qué tan completa está cada columna.
* Luego, con `completitud.idxmin()` se identifica el nombre de la columna que tiene el porcentaje de completitud más bajo, es decir, la que tiene proporcionalmente más datos faltantes. Finalmente, con `completitud.min() ` se obtiene el porcentaje mínimo de completitud para saber qué tan completa está esa columna.

---
## Actividad 6 — Exploración categórica

*Dataset: Customer Personality Analysis*

Aplica `.value_counts()` sobre la columna `Marital_Status` de `df_marketing`. Vas a encontrar, junto a las categorías esperadas (`Married`, `Single`, `Together`, `Divorced`, `Widow`), tres valores que claramente son errores de captura reales: `Alone`, `Absurd` y `YOLO`. Decide y justifica en una línea: ¿los eliminarías, los reclasificarías (por ejemplo, `Alone` → `Single`), o los dejarías así? No hay una única respuesta correcta — lo que importa es la justificación.

In [ ]:
# Tu código aquí
df_marketing['Marital_Status'].value_counts() #Para encontrar las categorias

Marital_Status
Married     864
Together    580
Single      480
Divorced    232
Widow        77
Alone         3
Absurd        2
YOLO          2
Name: count, dtype: int64

¿los eliminarías, los reclasificarías (por ejemplo, Alone → Single), o los dejarías así?

In [ ]:
print("Reclasificaría Alone como Single porque son categorías similares,")
print("y convertiría Absurd y YOLO en valores nulos porque no representan un estado civil válido.")

Reclasificaría Alone como Single porque son categorías similares,
y convertiría Absurd y YOLO en valores nulos porque no representan un estado civil válido.

In [ ]:
import numpy as np
df_marketing['Marital_Status'] = df_marketing['Marital_Status'].replace({
    'Alone': 'Single', #Single representa un estado igual que solo
    'Absurd': np.nan, #No representa ningun estado civil
    'YOLO': np.nan #No representa ningun estado civil
})

df_marketing['Marital_Status'].value_counts() #Para verificar los cambios

Marital_Status
Married     864
Together    580
Single      483
Divorced    232
Widow        77
Name: count, dtype: int64

---
---
*  Con este código primero reviso la columna Marital_Status con `.value_counts()` para conocer las diferentes categorías que contiene y detectar posibles errores. Después decido que Alone se puede cambiar por Single porque ambos representan que la persona está sola, mientras que Absurd y YOLO no representan estados civiles válidos, por lo que los convierto en valores nulos usando `np.nan.` Para poder usar np.nan, primero importo la librería numpy con `import numpy as np`. Luego, con `.replace()` hago los cambios directamente en la columna Marital_Status. Finalmente, vuelvo a utilizar `.value_counts()` para comprobar que los cambios se realizaron correctamente y verificar cómo quedaron las categorías.
---
---

---
## Actividad 7 — Consistencia de formato/patrón

*Dataset: Netflix*

La columna `show_id` debería seguir siempre el patrón: la letra `s` seguida de uno o más dígitos (`s1`, `s2`, ..., `s8807`). Verifica con `.str.match(r'^s\d+$')` si todos los valores cumplen esta convención. Reporta el porcentaje de cumplimiento.

In [ ]:
# Tu código aquí
n=df_netflix['show_id'].str.match(r'^s\d+$').sum() #Asignación de conteo para cumplimiento de match ^s\d+$
porcentaje_cumplimiento=n/len(df_netflix)*100 #Calculo del porcentaje
print("Valore que cumplen regla de s...:", n) #valor de concidenica
print("Total de filas en dataset:", len(df_netflix)) #total de datos
print("Porcentaje de cumplimiento:", porcentaje_cumplimiento,"%") #porcentaje final

Valore que cumplen regla de s...: 7787
Total de filas en dataset: 7787
Porcentaje de cumplimiento: 100.0 %

---
---
* El código de la Actividad 7 revisa la columna show_id para saber cuántos registros cumplen con el formato de comenzar con “s” y continuar con números. La función `match` compara cada dato con ese patrón, mientras que `sum `cuenta los registros que sí coinciden (ya que la función por si misma da valores boleanos).
* Por su parte `len` obtiene el total de filas y se utiliza para calcular el porcentaje de cumplimiento.
* En los `print ` se muestra la cantidad de registros correctos, el total de filas y el porcentaje obtenido para verficiar visualmente el resultado.
---
---

---
## Actividad 8 — `.info()` y `.describe()`

*Dataset: Customer Personality Analysis*

Ejecuta `.describe()` sobre la columna `Year_Birth` de `df_marketing` (puedes hacerlo con `df_marketing[['Year_Birth']].describe()`). Observa el valor mínimo (`min`). ¿Tiene sentido ese año de nacimiento? Filtra el DataFrame para mostrar las filas con los años de nacimiento más antiguos y decide, en una línea, si los considerarías un error de captura.

In [ ]:
# Tu código aquí
df_marketing[['Year_Birth']].describe() #Para observar la información general (estadistica)

        Year_Birth
count  2240.000000
mean   1968.805804
std      11.984069
min    1893.000000
25%    1959.000000
50%    1970.000000
75%    1977.000000
max    1996.000000

In [ ]:
# Tu código aquí Filtra el DataFrame para mostrar las filas
#con los años de nacimiento más antiguos
df_marketing.nsmallest(10, 'Year_Birth')[['Year_Birth']] #para buscar los 10 valores más pequeños de la columna Year_Birth

      Year_Birth
239         1893
339         1899
192         1900
1950        1940
424         1941
39          1943
358         1943
415         1943
894         1943
1150        1943

En este caso, no eliminaría los registros de años de nacimiento antiguos sin tener más contexto sobre el dataset. Aunque algunos valores pueden parecer errores de captura, siguen siendo datos que podrían ser útiles para comparar el rango de información. Primero revisaría el origen de los datos, el rango esperado y otras columnas relacionadas antes de decidir si se deben eliminar, corregir o tratar de otra manera. Por eso, considero que no es conveniente eliminar datos únicamente por parecer incorrectos en una sola columna, más aun considerando que el máximo se encuentra en 1996, primero preferiria saber el enfoque del análisis y los datos para tomar la desición.

---
---
El código de la Actividad 8 se utilizó de la siguiente forma:
* `df_marketing[['Year_Birth']].describe()` para obtener información estadística de la columna Year_Birth, como el mínimo, máximo, promedio y cantidad de datos. Esto ayuda a conocer el rango de los años.
* `df_marketing.nsmallest(10, 'Year_Birth')[['Year_Birth']]` para mostrar los 10 años de nacimiento más antiguos, permitiendo identificar valores que podrían ser inusuales.
* Sin embargo mi enfoque esta del lado de la exploración de los datos que la considero fundamental para la toma de decisiones de como tratar los datos ya que estas herramientas permitieron explorar los datos y detectar posibles errores antes de decidir si se deben eliminar o modificar y dado que no se tiene aun el contexto total de los datos se opto por no modificarlos aún, hasta mejorar el contexto y el fin del dataset.

---
## Actividad 9 — Práctica integradora: checklist de profiling

*Dataset: muestra real de Customer Personality Analysis, con 2 elementos inyectados y marcados a propósito (una fila duplicada y un valor de tipo incorrecto) para poder practicar el checklist completo con un resultado garantizado.*

Aplica el checklist completo, en orden, sobre `df_practica`:

1. Revisa `.dtypes` e identifica qué columna tiene un problema de tipo, corrígela con `pd.to_numeric(errors='coerce')`
2. Cuenta las filas duplicadas y elimínalas con `.drop_duplicates()`
3. Cuenta los valores faltantes por columna con `.isnull().sum()` (incluyendo el que se generó en el paso 1)
4. Revisa `.unique()` sobre `Marital_Status` y decide si necesita normalización

Al final, escribe un breve "reporte de profiling" (3-4 líneas) resumiendo qué encontraste y qué decidiste.

In [ ]:
# Muestra real con 2 elementos inyectados (marcados abajo)
df_practica = df_marketing.sample(15, random_state=3).reset_index(drop=True).copy()

# Elemento inyectado 1: una fila duplicada
df_practica = pd.concat([df_practica, df_practica.iloc[[2]]], ignore_index=True)

# Elemento inyectado 2: un valor de tipo incorrecto en Income
df_practica['Income'] = df_practica['Income'].astype(object)
df_practica.loc[5, 'Income'] = 'sesenta mil'

df_practica[['ID', 'Marital_Status', 'Income']]

       ID Marital_Status       Income
0    5788       Together      46053.0
1    7930         Single      26877.0
2    4557       Together      22070.0
3    9964         Single      61825.0
4    1168        Married      72159.0
5    5314       Together  sesenta mil
6    9665       Divorced      54237.0
7    6182       Together      26646.0
8     922        Married      31086.0
9    4427         Single      83257.0
10  10965       Together      76005.0
11   3074        Married      70643.0
12   6606        Married      70091.0
13   8148       Together      50898.0
14   4437        Married      65316.0
15   4557       Together      22070.0

In [ ]:
# Paso 1 — ajuste de tipos
df_practica.dtypes #para observar cuales columnas son objet pero no deberian ser

ID                      int64
Year_Birth              int64
Education              object
Marital_Status         object
Income                 object
Kidhome                 int64
Teenhome                int64
Dt_Customer            object
Recency                 int64
MntWines                int64
MntFruits               int64
MntMeatProducts         int64
MntFishProducts         int64
MntSweetProducts        int64
MntGoldProds            int64
NumDealsPurchases       int64
NumWebPurchases         int64
NumCatalogPurchases     int64
NumStorePurchases       int64
NumWebVisitsMonth       int64
AcceptedCmp3            int64
AcceptedCmp4            int64
AcceptedCmp5            int64
AcceptedCmp1            int64
AcceptedCmp2            int64
Complain                int64
Z_CostContact           int64
Z_Revenue               int64
Response                int64
dtype: object

In [ ]:
# Paso 1 — ajuste de tipos
df_practica['Income'] = pd.to_numeric(df_practica['Income'], errors='coerce')
df_practica['Dt_Customer'] = pd.to_datetime(df_practica['Dt_Customer'], errors='coerce')

#pd.to_numeric() para convertir los valores a numericos
# errors='coerce' para los que no se puen convertirlos a NaN
df_practica[['Income', 'Dt_Customer']]

     Income Dt_Customer
0   46053.0  2013-02-17
1   26877.0  2013-08-19
2   22070.0  2013-10-04
3   61825.0  2013-08-07
4   72159.0  2012-10-29
5       NaN  2013-03-18
6   54237.0  2013-04-27
7   26646.0  2014-02-10
8   31086.0  2013-05-04
9   83257.0  2012-09-18
10  76005.0  2013-02-22
11  70643.0  2012-10-15
12  70091.0  2013-03-31
13  50898.0  2013-01-08
14  65316.0  2013-04-24
15  22070.0  2013-10-04

In [ ]:
#Comprobar cambios
df_practica.dtypes

ID                              int64
Year_Birth                      int64
Education                      object
Marital_Status                 object
Income                        float64
Kidhome                         int64
Teenhome                        int64
Dt_Customer            datetime64[ns]
Recency                         int64
MntWines                        int64
MntFruits                       int64
MntMeatProducts                 int64
MntFishProducts                 int64
MntSweetProducts                int64
MntGoldProds                    int64
NumDealsPurchases               int64
NumWebPurchases                 int64
NumCatalogPurchases             int64
NumStorePurchases               int64
NumWebVisitsMonth               int64
AcceptedCmp3                    int64
AcceptedCmp4                    int64
AcceptedCmp5                    int64
AcceptedCmp1                    int64
AcceptedCmp2                    int64
Complain                        int64
Z_CostContact                   int64
Z_Revenue                       int64
Response                        int64
dtype: object

In [ ]:
# Paso 2 — duplicados
#Contar las filas duplicadas
print("Filas duplicadas al inicio:", df_practica.duplicated().sum())

#Eliminar filas duplicadas
df_practica = df_practica.drop_duplicates()
print("Filas duplicadas al final con tratamieto:", df_practica.duplicated().sum())

Filas duplicadas al inicio: 1
Filas duplicadas al final con tratamieto: 0

In [ ]:
# Paso 3 — valores faltantes
df_practica.isnull().sum() #para contar los valores faltantes por columna

ID                     0
Year_Birth             0
Education              0
Marital_Status         0
Income                 1
Kidhome                0
Teenhome               0
Dt_Customer            0
Recency                0
MntWines               0
MntFruits              0
MntMeatProducts        0
MntFishProducts        0
MntSweetProducts       0
MntGoldProds           0
NumDealsPurchases      0
NumWebPurchases        0
NumCatalogPurchases    0
NumStorePurchases      0
NumWebVisitsMonth      0
AcceptedCmp3           0
AcceptedCmp4           0
AcceptedCmp5           0
AcceptedCmp1           0
AcceptedCmp2           0
Complain               0
Z_CostContact          0
Z_Revenue              0
Response               0
dtype: int64

In [ ]:
# Paso 4 — exploración categórica
df_practica['Marital_Status'].unique()  #ver categorías escritas de diferentes maneras

array(['Together', 'Single', 'Married', 'Divorced'], dtype=object)

In [ ]:
df_practica[['ID', 'Marital_Status', 'Income']]

       ID Marital_Status   Income
0    5788       Together  46053.0
1    7930         Single  26877.0
2    4557       Together  22070.0
3    9964         Single  61825.0
4    1168        Married  72159.0
5    5314       Together      NaN
6    9665       Divorced  54237.0
7    6182       Together  26646.0
8     922        Married  31086.0
9    4427         Single  83257.0
10  10965       Together  76005.0
11   3074        Married  70643.0
12   6606        Married  70091.0
13   8148       Together  50898.0
14   4437        Married  65316.0

**Tu reporte de profiling:**
En la exploración de la muestra de Customer Personality Analysis se encontró que la mayoría de los datos de Income son valores numéricos, aunque un registro quedó como NaN después de convertir un dato incorrecto. También se identificó y eliminó una fila duplicada durante la limpieza. En Marital_Status se encontraron las categorías Together, Single, Married y Divorced, las cuales se mantienen porque representan diferentes situaciones. En general, la muestra presenta datos utilizables, pero es importante revisar los valores faltantes y los posibles errores antes de realizar un análisis más profundo asi como conocer el conxto del mismo.

---
---

* Para el código de la Actividad 9 primero se revisaron los tipos de datos con `.dtypes` para identificar posibles problemas en las columnas. Se encontró que Income contenía un valor de texto, por lo que se utilizó `pd.to_numeric(errors='coerce')` para convertir la columna a valores numéricos; el dato que no pudo convertirse pasó a ser NaN, es decir, un valor faltante.
* Se utilizó `.duplicated().sum()` para contar las filas repetidas y .`drop_duplicates()` para eliminar el registro duplicado.
* C .`isnull().sum()` se revisaron los valores faltantes generados.
* Por su parte se utilizó .unique() para observar las categorías de Marital_Status, encontrando Together, Single, Married y Divorced, que son categorías diferentes y consistentes, por lo que no fue necesario normalizarlas.